sonar.projectKey=mlpipeline
sonar.projectName=MLPipeline
sonar.projectVersion=1.0

sonar.sources=src,serving,dags
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10

sonar.exclusions=\
  data/**,\
  models/**,\
  notebooks/**,\
  helm/**,\
  kubernetes/**,\
  argocd/**,\
  **/__pycache__/**,\
  **/migrations/**

sonar.coverage.exclusions=\
  tests/**,\
  dags/**,\
  serving/Dockerfile
