apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webserver-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: airflow
    component: webserver
type: Opaque
stringData:
  secret-key: {{ .Values.webserver.secretKey | required "webserver.secretKey is required" | quote }}
