apiVersion: v1
kind: Secret
metadata:
  name: bea-api-credentials
  namespace: mlpipeline
  labels:
    app.kubernetes.io/name: mlpipeline
    app.kubernetes.io/component: etl
type: Opaque
stringData:
  BEA_API_KEY: "E10CDAEF-CC7D-4DDA-BB9B-04FB8FBE0C9E"
