apiVersion: v1
kind: Namespace
metadata:
  name: mlpipeline
  labels:
    app.kubernetes.io/name: mlpipeline
    app.kubernetes.io/component: core
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: helm
